version: '3.8'

services:
  image-overlay:
    build: .
    image: image-overlay-app
    container_name: image-overlay-app
    environment:
      - DISPLAY=host.docker.internal:0
    volumes:
      - .:/app
      - /tmp/.X11-unix:/tmp/.X11-unix
    devices:
      - /dev/dri:/dev/dri
    network_mode: host

    